### ISSUE TITLE
Cannot push to repository

### ISSUE THREAD

**Issue by deqenq** [cake-contrib/Cake.Wget#2]
@gep13 I wanted to update links in readme after moving repository to `cake-contrib`, but I have found that I cannot do `git push` with error: 
```
 "C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "origin" refs/heads/master:refs/heads/master
remote: Permission to cake-contrib/Cake.Wget.git denied to deqenq.
fatal: unable to access 'https://github.com/cake-contrib/Cake.Wget.git/': The requested URL returned error: 403
```
I tried also to push to new branch with the same result. I checked the GitHub settings and it seems that I have Admin role. Please could you help me with this?

**Comment by gep13** [comment]
@deqenq this is very strange!  From what I can see, you have the correct access, so there should be nothing to stop you doing the push.

How are you authenticating to GitHub?  Is it with a PAT or with username/password?  If with a PAT, it might be that you need to re-generate it since being added to the Organisation.  I haven't heard of any problems with any other people who have joined the Organisation.  Are you in a position to test from another machine?  To rule out something on that computer you are using?

@cake-contrib/team anyone else have any suggestions about what else to check?

**Comment by deqenq** [comment]
@gep13 I can commit directly through github web interface (I updated readme). I will investigate the client settings (I use GitExtensions or SmartGit). I authenticate using username/password. Other repositories on github are working for me, only Cake.Wget refuses me.

**Comment by gep13** [comment]
@deqenq hmm, even stranger!  The fact that you can commit through the Web UI, and also that you can add labels to this issue, tells me that you have the right access, so that only leaves something on the client environment that isn't "quite" right.

Did you make a fresh clone of the repository after it was transferred to the `cake-contrib` org, or did you modify the existing one?

**Comment by deqenq** [comment]
@gep13 I tried fresh clone without success. Currently I am not sure where to start investigating. I will try it with clean virtual machine.

**Comment by gep13** [comment]
@deqenq are you still using SmartGit?  Can you confirm if you have directly tried a `git push` command by itself?

**Comment by deqenq** [comment]
@gep13 I resolved the issue. The problem was that SmartGit is registered application and it needed to re-register with new authorization token ([docs here](https://www.syntevo.com/doc/display/SG/GitHub+integration)). I completely forgot about it, my mistake. Thank you for your hints where to search the problem, that helped me. I am sorry to waste your time :-(

**Comment by gep13** [comment]
@deqenq glad to hear that you got this working!  Let me know here, or via Slack, if you have any other questions about anything.
